name: Trigger TSDoc Generation

on:
  push:
    branches:
      - master

jobs:
  trigger-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger repository_dispatch event in doc repo
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.FROLICCHAT_TSDOC_WRITE }}
        repository: Frolic-chat/frolic-chat.github.io
        event-type: generate-docs
